### ISSUE TITLE
Funcionamiento deudas y pagos futuros

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC3745-2020-2/syllabus#1]
Hola!
Con mi grupo revisamos el enunciado y no nos quedó muy claro como funcionan las deudas. En especifico, ¿El deudor debe pagar las deudas? ¿Existen fechas de pago o fechas límites? Lo mismo con los pagos futuros de la cuenta crédito ¿Las cuotas se descuentan automaticamente en ciertas fechas? Ojalá puedan aclarar más sobre estos temas.

Y por último, ¿se recomienda modelar las transacciones como un conjunto o separar cada una de ellas?
Gracias!!

**Comment by iaacosta** [comment]
Hola @Marialuisaclaro!

La idea de los préstamos y deudas es tener una idea mas real de cuánto dinero tengo hoy en mi cuenta y que es realmente mio. Si prestara dinero, en realidad tengo mas de lo que sale en mis cuentas, y si debiera, tengo menos.

En vez de hacer el proceso mental de "Juanito me debe algo, debo cobrarle", este tipo de transacción en la plataforma cumple esa función _recordatoria_ y además lleva un registro.

El acreedor/deudor puede no estar registrado en la plataforma, y como la transacción se pensó en un contexto mas informal, no es necesario que haya fecha límite. Respecto a si debe pagar o no, depende del deudor (quizás a quien le prestaste nunca devuelve, o quizás si, depende de cuánto lo/la presiones en la vida real).

Lo automático **de la liquidación** de las cuotas (paso de saldo no liquidado a saldo liquidado) no es necesario. Notar que esto es distinto a como manejan la transacción en cuotas al momento de crearse (podrían crear _n_ transacciones para una compra en _n_ cuotas, hacer una transacción especial, etc.)

Para las cuentas de crédito, en la práctica existe una fecha de pago límite y posterior a eso se cobra un interés. A modo de ejemplo, en la plataforma se puede hacer una transacción a mano para reflejar este interés sin necesidad de usar las fechas.

La idea de la aplicación es poder llevar un registro minucioso, por eso se incorporan estos detalles. Les recalco igual que está es la complejidad esperada, si creen que hay otra forma de representar mejor estas deudas y préstamos, pueden proponerla a su ayudante. Si la complejidad y capacidad de casos de prueba no baja y su ayudante está de acuerdo, pueden desarrollarla.

Finalmente, si modelar o no de manera separada, les recomiendo echarle una mirada a este blog que habla a grandes rasgos de como manejar transacciones en una app:

https://blog.platan.us/no-nos-ense%C3%B1aron-a-programar-con-plata-fcea5a9146bd

Es un buen primer approach de como hacer transacciones, pero ojo que no esperamos una modelación escalable y eficiente, la idea central del curso y del proyecto es que puedan testearla bien y aprendan de ello, siempre tengan eso en mente.

¡Avísame si no les queda claro para explicarlo de otra forma!

Saludos
