### ISSUE TITLE
Conditional Coverage 

### ISSUE THREAD

**Issue by pepina-dev** [IIC3745-2020-2/syllabus#10]
Repito algunas pregunta que hice hoy en la sesión de consultas:

1. ¿Las variables booleanas que no se prueban en ninguna condición, se consideran dentro de conditional coverage?
**Repuesta** (o lo que entendí, corríjanme si estoy mal): No, sólo las que están en alguna condición.

1. Dependiendo del lenguaje puede variar si se evalúan o no ciertas expresiones (Ej: A or B donde A es true). ¿Asumimos que el lenguaje evalúa sólo lo estrictamente necesario (sólo A si es true) o que evalúa ambos sin importar el valor  de A?
**Respuesta** ( o lo que entendí, corríajanme estoy mal): Hay que abstraerse del lenguaje, por eso se preguntaba por pseudocódigo. En el caso de A = true, en A or B, B sería una expresión  pasiva y sería activa cuando A es False.  Para tener 100% de conditional coverage tiene que evaluar también cuando B es activa. Entendí que esto corresponde al primer caso, en que sólo se evalúa lo estrictamente necesario (sólo se evalúan expresiones activas).

**Comment by Hernan4444** [comment]
Hola, confirmo que ambas respuestas está bien.

Para complementar el punto 2. Si tienen según el criterio de coverage que estemos trabajando, algunos test pueden llegar a ser redundantes por el tema de expresiones pasivas y activas. Por ejemplo, con `if A or B` y los siguientes casos:
1. A = True y B = True
2. A = True y B = False

Como el conditional coverage dice que por lo menos cada expresión se tiene que evaluar a True y a False, pero por como es la lógica solo con A = True, la expresión se evalúa como True y se entre a esa rama, por lo tanto, B nunca se cubre, así que basta con 1 de esos 2 test. Si se desea testear B (y cumplir con conditional coverage), se debería hacer alguno de los siguientes test:
1. A = False y B = True
2. A = False y B = False

Pero hay otro criterio más exigente donde es necesario probar todas las combinaciones posibles, lo que podría provocar que no sean redundante. Pero esos criterio son más costoso y para varios casos no aporta valor adicional que un criterio menos exigente.

Saludos :v:

**Comment by pepina-dev** [comment]
Gracias Hernán por la confirmación y el ejemplo!

**Comment by vmanriq** [comment]
Hola, tengo una duda con el ejemplo que planteaste debido a que si tan solo se realiza 1 de los segundos test que planteaste 
A = False y B = True
A = False y B = False 
nunca se evaluaría el B en true o en false dependiendo el que se elíga, según yo es necesario realizar esos test y elegir cualquiera de estos 
A = True y B = True
A = True y B = False
que son los que planteabas al inicio.

Aun que no estoy seguro

**Comment by rasaffie** [comment]
Hola Vicente,

Quizás no se entendió bien lo que quería explicar Hernán. Para el caso del _conditional coverage_ cada condicional se debe evaluar por lo menos una vez a `True` y una vez a `False`. Si el predicado es `A or B`, entonces se necesita que el conjunto de _tests_ cumplan por lo menos una vez con las evaluaciones `A == True`, `A == False`, `B == True` y `B == False`. 

Con las pruebas:

* `t1 = {A == True; B == True}` 
* `t2 = {A == False; B == False}` 

aún no se lograría el 100% de _conditional coverage_ a pesar de que a cada condicional se le hayan asignado sus valores posibles, ya que para el caso _t1_ no se evalúa `B = True` porque el predicado depende del valor de `A`. Para lograr 100% bajo _conditional coverage_ se necesitarían 3 _tests_:

* `t1 = {A == True; B == X}`, con `X = False` o `X = True`
* `t2 = {A == False; B == True}`
* `t3 = {A == False; B == False}`

Pienso que con el ejemplo que aparece [en el link](https://www.tutorialspoint.com/software_testing_dictionary/condition_coverage_testing.htm) que dejamos en el enunciado esto se ejemplifica mejor, porque se evalúa el predicado `(A || B) && C`.

En las próximas clases veremos más criterios de cobertura en base a expresiones lógica, donde para este mismo predicado sería necesario realizar más _tests_ para cumplir con 100% de cobertura.

Saludos!

**Comment by vmanriq** [comment]
Ok, ahora si entiendo. Gracias profe por aclarar la duda tan rapido :D
