### ISSUE TITLE
AC01 Cobertura Parte A - Cobertura de clase Book

### ISSUE THREAD

**Issue by pdesolminihac** [IIC3745-2020-2/syllabus#11]
Hola!

En la parte A de cobertura de la actividad se pide un 100% de cobertura en los 3 criterios. ¿Es esto para todo el bloque de código? o solo para el método `can_buy?`.

Gracias,

Patricio

**Comment by Hernan4444** [comment]
Hola, como se indica en #12, solo nos interesa que testean y aseguren la cobertura del método `can_buy` 😄 

Saludos :v:
