### ISSUE TITLE
Branch Coverage AC01 Parte A

### ISSUE THREAD

**Issue by pepina-dev** [IIC3745-2020-2/syllabus#12]
Repito una pregunta que hice hoy en la sesión de consultas:
Para el  criterio de branch coverage:  ¿Tenemos que probar sólo el método? ¿O a la declaración de la clase completa? Porque  esto afectaría la cantidad de ramas. Si fuese la clase completa se tiene que testear sólo la declaración de la clase (sólo Book sin crear ningún objeto) y sólo la inicialización de un objeto sin la llamada al método (sólo un Book.new para crear un objeto ). 

Respuesta (o lo que entendí, corríjanme si estoy mal):  No se espera que probemos sólo la clase o la inicialización de objetos por separado, tenemos que probar el método y el objeto es como un argumento de este.

**Comment by Hernan4444** [comment]
Confirmo la respuesta, nos basta con que prueben `can_buy` y para ello, será necesario modificar la instancia del libro para cambiar que volumen es o cuantos volumenes totales hay.

Saludos :v:

**Comment by pepina-dev** [comment]
Buenísimo, gracias!
