### ISSUE TITLE
AC01 - Fórmato de entrega de los casos de prueba

### ISSUE THREAD

**Issue by Jiruiz2** [IIC3745-2020-2/syllabus#13]
Hola,

Quería consultar como se debe entregar los casos de prueba que se piden. Por ejemplo, el siguiente formato es correcto:

Caso 1: Se prueba que la contraseña no es segura por X motivo.
Input: XXXXXXXX
output: False/True

O debe hacerse usando grafos como se vió en clases.

Saludos

**Comment by Hernan4444** [comment]
Hola, 

Esta bien ese formato. No hay que hacer grafos como los vistos en clases.

Saludos :v:
