### ISSUE TITLE
Enunciado proyecto (LIQUIDADOS y NO LIQUIDADOS)

### ISSUE THREAD

**Issue by stmorales** [IIC3745-2020-2/syllabus#15]
Hola!!

En nuestro grupo aparecieron algunas dudas respecto a lo que se espera respecto a los saldos liquidados y los no liquidados. No entendemos bien si por liquidado se refieren a la "caja disponible" que se tiene y por no liquidado se refiere a la fórmula: cuentas por cobrar - cuentas por pagar ?

Si nos pueden dar un ejemplo se los agradeceríamos mucho, ya que de esto va a depender el modelo de datos que utilizaremos. Muchas gracias!

**Comment by iaacosta** [comment]
¡Hola @stmorales!

¡Si! En términos contables nos referimos a eso mismo. Para ilustrarlo mejor con un ejemplo, supongamos tenemos los siguientes movimientos:

- Un gasto de 2.990
- Un ingreso de 50.000
- Un préstamo que hice por 5.000
- Una deuda pendiente por 10.000
- Una compra de crédito por 5.990

**Mi saldo liquidado sería** _ingreso - gasto = 50.000 - 2.990 = 47.010_
**Mi saldo no liquidado sería** _préstamo - (deuda + crédito) = 5.000 - (10.000 + 5.990) = -10.990_ 

Entonces, **el dinero que realmente es mio ahora** sería de $36.020, porque eventualmente tengo que cobrar y pagar mis obligaciones con terceros.

Espero les haya servido para entender mejor 😄 
Saludos

**Comment by stmorales** [comment]
Perfecto! Muchas gracias @iaacosta !! 

Nos queda una última duda. Cuando nosotros recibimos los pagos de los préstamos y pagamos las deudas y créditos. Esos son considerados ingresos y gastos respectivamente entonces?

Gracias!!

**Comment by iaacosta** [comment]
De nada!

Es válido, depende de ustedes como manejan la liquidación de estos saldos no liquidados. 

Lo importante es que el usuario pueda accionar algo para entender que esos movimientos ya fueron pagados.

Saludos!
