### ISSUE TITLE
AC01 Preguntas Conceptuales

### ISSUE THREAD

**Issue by vbarreradg** [IIC3745-2020-2/syllabus#16]
Hola! En la pregunta 4 de las preguntas conceptuales a qué se refiere el "enfoque" para los tests? A qué nivel de testing es más importante?
Gracias!

**Comment by rasaffie** [comment]
Hola,

Esta pregunta se refiere a los conceptos que vimos en la clase 3, donde introducimos los 4 niveles tradicionales de _testing_, además de algunos enfoques de cómo se pueden aplicar según distintos objetivos.

Saludos,
