### ISSUE TITLE
Permisos para crear app en Heroku

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC3745-2020-2/syllabus#17]
Hola!

Traté de crear la app en Heroku pero me dice que no tengo acceso para eso. Está bien configurado el repo?
Gracias!

---

**PD:** Adjunto foto con donde se detalla que no tengo permisos de esta organización

![Screen Shot 2020-09-05 at 02 32 20](https://user-images.githubusercontent.com/26119673/92299458-50188e80-ef20-11ea-9031-f2a81e670037.png)

**Comment by rasaffie** [comment]
Hola Felipe,

No podrán configurar el _deploy_ de su aplicación desde el _dahsboard_ de Heroku porque no cuentan con los permisos necesarios sobre el repositorio.

Por esta razón, deberán configurar el _deploy_ a través de GitHub Actions, como se indica en [este enlace](https://github.com/marketplace/actions/deploy-to-heroku). Sin embargo, tendrán que coordinar con su ayudante para que él agregue una _API key_ como secreto al repositorio, para que así no la escriban textual en el código. Pueden enviársela a través del correo, una _issue_ o darle acceso a la aplicación de Heroku para que él acceda directamente (aunque tienen que coordinar este tema directamente con él).

Saludos,

**Comment by fdominguezclaro** [comment]
Gracias por la respuesta y el link! 
Buen fin de semana!
