### ISSUE TITLE
Grafo Parte B 

### ISSUE THREAD

**Issue by Marialuisaclaro** [IIC3745-2020-2/syllabus#18]
Hola!
Tengo una duda de la Parte B de la Actividad. ¿Existe un número máximo de variables que podemos evaluar en cada arista? Dependiendo de cuantas condiciones ponemos en cada arista, será la cantidad de aristas que hay en el grafo. Y depende de las aristas y la forma del grafo los resultados del Condition y Branch Coverage. Entonces depende de como modelamos el problema, los resultados del Coverage (¿Esta bien eso?)

Gracias!

**Comment by rasaffie** [comment]
Hola,

No existe un número máximo de variables que puedan evaluar por arista, depende de cómo prefieran modelar su flujo solamente. Piensen que los operadores `&&` y `||` son elementos sintácticos para evitar código duplicado, pero se podría escribir la misma funcionalidad con más líneas de código sin utilizar estos operadores.

Realizar un grafo más desagregado (en que cada arista evalúa una sola condición) puede ser más conveniente para evaluar la cobertura en base a condicionales, pero no será un aporte para evaluar cobertura en base a nodos o a aristas (en que cada arista representa el resultado de cada predicado completo). Sin embargo, modelar el grafo de esta forma no es un requisito y ambos criterios se pueden evaluar según un mismo grafo.

Como la cobertura es una proporción entre el código total y el código ejecutado durante los casos de prueba, el valor exacto de esta proporción depende directamente de la cantidad de código. Por esta razón, el porcentaje exacto de cada criterio de cobertura dependerá directamente de cómo modelen y escriban su código. Sin embargo, esta diferencia no es relevante porque los valores de los porcentajes de cobertura no son comparables entre distintos criterios: el valor de la proporción solamente indica que bajo un mismo criterio un conjunto de pruebas abarca más (o menos) código fuente que otro conjunto de pruebas.

Saludos,
