### ISSUE TITLE
Categorias de Ingresos y Gastos

### ISSUE THREAD

**Issue by pdesolminihac** [IIC3745-2020-2/syllabus#2]
Hola!

En el enunciado del proyecto dicen:
_"El usuario debe poder categorizar sus gastos e ingresos"_

¿A que se refieren con esto?

**Comment by iaacosta** [comment]
Hola @pdesolminihac!

Nos referimos a que, a través del administrador, se puedan manejar una serie de categorías de gastos e ingresos para que los usuarios comunes de la app puedan _tagear_ sus transacciones y así tener una mejor clasificación.

Por ejemplo, el admin puede crear la categoría "Comida", y un usuario podría indicar en la plataforma que gastó 2.990 de su cuenta vista en "Comida".

Si no te queda claro, avísame!

Saludos
