### ISSUE TITLE
Subir actividad hecha en pareja

### ISSUE THREAD

**Issue by javierairarrazabal** [IIC3745-2020-2/syllabus#20]
Hola! 
Perdón la hora pero me entró la duda de, si es que se hizo la actividad en parejas, ambas personas deben subir la actividad a Canvas, o solo un integrante.
Muchas Gracias!

**Comment by Hernan4444** [comment]
Hola, solo uno debe entregar, pero dentro del PDF debe tener el nombre de su compañero. Ideal si también ponen el mail y/o número de alumno, asi es más facil hacer match con su pareja cuando tengamos las notas.

Saludos :v:

**Comment by javierairarrazabal** [comment]
Muchas Gracias!!!
