### ISSUE TITLE
Test para Gema Devise

### ISSUE THREAD

**Issue by juanfcolopez** [IIC3745-2020-2/syllabus#21]
Hola!

Una consulta, si tenemos pensado utilizar la gema devise para el manejo de sesiones, es necesario realizar los test correspondientes a estas funcionalidades? 

muchas gracias.

**Comment by iaacosta** [comment]
Hola @juanfcolopez!

Dado que es una librería externa, no es necesario que se hagan tests exhaustivos de las funcionalidades que te dan, pues ya lo hizo el equipo desarrollador a cargo de la gema y tienen sus metodologías para asegurar la calidad del código.

Pero, si realizan cambios sobre `Devise` (alguna vista/ruta/controlador adicional o una adición/cambio al modelo), es necesario que hagan las pruebas para asegurar que sus cambios funcionan y se integran bien con la librería.

A modo de ejemplo:
- Si [extrajeran las vistas de `Devise`](https://github.com/heartcombo/devise#configuring-views) para hacerles cambios en la lógica, contenido o estilo, deben testear esos cambios. Lo mismo aplica para controlador y modelo.
- Si crearan una ruta y vista de inicio que contiene un link al _sign up_ / _log in_ / _log out_ de `Devise`, debieran testear el _render_ de esos links y que las rutas de destino sean correctas.

Espero haber aclarado tus dudas :smile: 
Saludos

**Comment by juanfcolopez** [comment]
Sii! 
Muchas graciasss!

**Comment by rasaffie** [comment]
Para complementar la respuesta de Ignacio: no es necesario probar la lógica interna de las librerías que importen si es que confían en sus desarrolladores/mantenedores, pero sí se puede probar la forma en que su aplicación interactúa con estas librerías.
