### ISSUE TITLE
[Enunciado][Entrega 1] Planificación de funcionalidades - Nivel de detalle

### ISSUE THREAD

**Issue by B-Dominguez** [IIC3745-2020-2/syllabus#22]
Hola,

Quisiéramos saber qué nivel de detalle se espera para la planificación de funcionalidades a entregar en la E1. Por ejemplo, podrían ser las funcionalidades a nivel macro estimadas para cada sprint (entrega). También, quisiéramos saber si se espera algún mecanismo formal de estimación de esfuerzo para la planificación (como puntos de desarrollo por relato de usuario).

Gracias!

**Comment by iaacosta** [comment]
Hola @B-Dominguez!

Esperamos que entreguen los relatos de usuario divididos en las distintas entregas restantes (E2, E3 y E4), no es necesario un nivel mayor de especificación ni justificación. Consideren que, al menos, la idea es dividirlas equitativamente en número y no cargar una entrega específica.

Respecto a la estimación: no lo exigimos ni tampoco lo evaluaremos, pero si ustedes quieren establecer algún metodo formal/informal para manejar los esfuerzos requeridos internamente, pueden hacerlo.

Saludos!

**Comment by B-Dominguez** [comment]
Gracias @iaacosta, me queda muy claro!
