### ISSUE TITLE
Tests para esta entrega

### ISSUE THREAD

**Issue by valerojasm** [IIC3745-2020-2/syllabus#23]
Hola!

Para esta entrega, está considerado tener tests de modelos, controladores, vistas y rutas. Teniendo en cuenta que lo mínimo requerido en cuanto a la app en si ahora es solo el CRUD de usuarios y manejo de sesión, estos tests se refieren a llevar una especie de TDD y tenerlos todos listos desde antes? O solo los tests del modelo de user? Si es esto último, qué habría que testear específicamente? Lo que fue nombrado en una issue anterior (atributos o métodos extra de devise) solamente?

Muchas gracias!

**Comment by rasaffie** [comment]
Hola,

Para cada entrega se les pide que hagan tests de los modelos, controladores, vistas y rutas de las funcionalidades que hayan desarrollado, no se les pedirá que aborden su desarrollo bajo la metodología TDD. Se detallan estos elementos en específico porque no se les exigirán tests de otros componentes de Rails, como por ejemplo los _mailers_, _assets_ o _channels_.

Por lo tanto, para esta entrega se les pide que testeen por lo menos los modelos, controladores, vistas y rutas relacionados al CRUD de usuarios y sus sesiones.

Si bien Devise realiza varias funcionalidades relacionadas a las sesiones de usuarios, hay acciones que tendrán que desarrollar y testear ustedes mismos (como el _show_ o _destroy_ de un `User`).
