### ISSUE TITLE
Error en Tests de GitHub después de un push

### ISSUE THREAD

**Issue by juanfcolopez** [IIC3745-2020-2/syllabus#24]
Hola!

Tengo el siguiente problema, luego de hacer push del código por haber hechos unos cambios, se comienzan a correr los test en GitHub y nos muestra el siguiente error en uno de ellos:
![image](https://user-images.githubusercontent.com/42149950/92778696-caf60500-f377-11ea-9955-d33a06c964e6.png)

Saben a qué se debe y cómo se podría arreglar? 

Muchas gracias

**Comment by rasaffie** [comment]
Hola,

Sospecho que su problema se debe a que copiaron el archivo `config/credentials.yml.enc` desde el repositorio de ejemplo, pero no tienen una llave válida para desencriptarlo. Tienen que crear su propio par de archivos para credenciales y llaves como se explica en el _issue_ https://github.com/IIC3745-2020-2/syllabus/issues/14, y configurar su llave como un secreto en GitHub Actions.

Al parecer cuando agregan Devise es necesario que las credenciales estén bien configuradas para que puedan ejecutar su aplicación. Confirmame si al hacer esto se soluciona el problema.

Saludos,

**Comment by juanfcolopez** [comment]
Hola Profesor!

Justamente era eso. No habíamos hecho envío de nuestras credenciales para integrarlas en Github Actions.

Muchas gracias por la ayuda!
