### ISSUE TITLE
[Entrega 1] Deploy a Heroku y Coverage 100%

### ISSUE THREAD

**Issue by mimunoz11** [IIC3745-2020-2/syllabus#25]
Hola, esperando que estén todxs bien.

Quisieramos preguntar por 2 cosas:

1) ¿Es posible hacer un push a master para probar si la configuración del Deploy es correcta?

2) Llevamos implementados varios test de los enseñados hoy en la mañana, pero el coverage no aumenta tan rápido ¿hay algún consejo para aumentarlo o ver especificamente cuales son los test que falta por cubrir para llegar al 100%?

Saludos,

**Comment by B-Dominguez** [comment]
Hola, soy alumno también pero para probar el deploy en master sin arruinar el GitFLow he estado haciendo los commits y después uso git reset --hard y git push --force (no son las mejores prácticas, pero muy útiles)

**Comment by rasaffie** [comment]
Hola,

1. La forma "más correcta" de probar el _deploy_ a Heroku es cambiando la configuración de tu _workflow_ de _deploy_ para que se ejecute sobre otra _branch_ que no sea _master_ mientras lo pruebas. De todas formas les pido hagan a conciencia estas pruebas porque tenemos minutos limitados de CI dentro de la organización.
2. Dependiendo de las funcionalidades que hayan programado quizás sea necesario desarrollar más _tests_ de los que vimos en la clase de ayer. Independiente a eso, Simplecov genera la carpeta `coverage` en el _root_ de tu proyecto una vez que ejecutas los _tests_, en donde el archivo `index.html` muestra el detalle de la cobertura sobre tu código. De esta forma puedes visualizar qué partes de tu código no están siendo probadas.

Saludos,
