### ISSUE TITLE
Deploy con Docker

### ISSUE THREAD

**Issue by B-Dominguez** [IIC3745-2020-2/syllabus#26]
Hola,

En mi grupo y otros con los que he conversado hemos tenido problemas para hacer el deploy a Heroku con Docker (no por la configuración de la Action, si no porque no se realiza el build correctamente [en mi caso en Heroku solo se hace deploy pero no intenta el build] ).

Quisiera saber si es requisito que el deploy sea con docker, y/o si nos podrían guiar un poco con la configuración del repositorio y en Heroku para que el deploy con Docker funcione.

Muchas gracias,

Benjamín Domínguez

**Comment by Marialuisaclaro** [comment]
Hola! Me sumo a la consulta. Tampoco me ha funcionado

**Comment by rasaffie** [comment]
Hola,

No es necesario hacer _deploy_ con Docker. Si alguien lo hizo así y puede resolver esta duda es bienvenido a hacerlo.

De todas formas prueba haciendo el _deploy_ sin Docker porque sospecho que el problema que tienes es con la configuración de Heroku (por ejemplo, revisa la configuración de tu Procfile).

Saludos,
