### ISSUE TITLE
Test modelos repositorio de ejemplo

### ISSUE THREAD

**Issue by bawas** [IIC3745-2020-2/syllabus#27]
Estaba repasando la clase del lunes, y me surgió una duda respecto a las pruebas de _should have_db_column_ asociadas al modelo **Commit** del repositorio de ejemplo. No debiese haber una prueba que tenga como objetivo al atributo **pushed_at** de la forma _should have_db_column(:pusheda_at)_ ?

Saludos!

**Comment by rasaffie** [comment]
Sí, me faltó agregar esa prueba. 

La dificultad al probar elementos que son parte de las definiciones de clases (como los atributos, sus validaciones o sus asociaciones) es que estas líneas se ejecutan siempre que la aplicación se ejecuta. Por esta razón es difícil verificar si es que falta algún _test_ sobre uno de estos conceptos porque la herramienta de _coverage_ no lo detecta (a diferencia de las líneas de código dentro de un método).

**Comment by bawas** [comment]
gracias!
