### ISSUE TITLE
A01 - Criterio de Seguridad de Letras

### ISSUE THREAD

**Issue by felipegarcia98** [IIC3745-2020-2/syllabus#3]
En el enunciado de la actividad, en la parte de Diseño de Pruebas, sale que el criterio de seguridad es "que haya una letra mayúscula o minúscula", lo cual sería lo mismo a "que haya una letra", por lo que me surge la duda si se referían precisamente a eso, a que hubiera una letra de tamaño diferente al resto de las letras que hayan o a otra cosa.

**Comment by Hernan4444** [comment]
Hola, 

Fue un typo nuestro. Acabamos de actualizar el enunciado en donde se cambió ese `o` por un `y`. La idea es que haya una letra mayúscula y otra minúscula.

Saludos :v:

**Comment by felipegarcia98** [comment]
@Hernan4444  sin límite de letras mientras cumpla los otros criterios, no? es decir, es minimo una para minúsculas y mayúsculas, no?

**Comment by Hernan4444** [comment]
@felipegarcia98 así es. No hay un límite. Basta con tener una letra mayúscula y otra letra minúscula para cumplir ese requisito. 

Saludos :v:
