### ISSUE TITLE
Tests modelo user

### ISSUE THREAD

**Issue by javierairarrazabal** [IIC3745-2020-2/syllabus#30]
Hola!
Para esta entrega se deben hacer solo los test de routes, models, views y controllers relcionados con el usuario? Pregunto porque también creamos otros modelos como deuda, transacción, etc.
Muchas Gracias!

**Comment by Hernan4444** [comment]
Hola!,

Para esta entrega solo esperamos que testeen y cumplan con el 100% de coverage con lo pedido (usuario y sesiones). No obstante, recuerda que los test están seteados para que solo se ejecuten los demás si tienen 100% de cobertura. Si deciden subir a master los otros modelos que crearon, ya no cumplirán con ese porcentaje y github actions no correrá todos sus test.

Dado lo anterior, si quieren subir los otros modelos que hicieron: **solo para esta entrega** pueden bajar el requisito del 100% de cobertura en SimpleCov y así github actions corra todos sus test. Nosotros evaluaremos que cumplan con 100% en lo que respecta a usuario y sesiones.

Finalmente, para la entrega 2 (y todas en adelante), se exigirá que todo lo implementado esté testeado. Por lo tanto, desde la entrega 2 en adelante,  si deciden avanzar en más funcionalidades, deberán ser testeadas para cumplir con los requisitos mínimos y 100% de coverage.

Saludos :v:
