### ISSUE TITLE
Correlated active clause coverage

### ISSUE THREAD

**Issue by vmanriq** [IIC3745-2020-2/syllabus#37]
Hola, tengo una duda con respecto a CAAC, debido a que  se pide  que la clausula mayor sea evaluada en `True` y en `False` y como algo adicional menciona que el predicado debe quedar evaluado en `True` y en `False`. Mi duda va con respecto a que el predicado obligatoriamente debería cambiar si evaluamos a la clausula mayor en los dos valores, por definición de clausula mayor, entonces por que se menciona como un adicional ? 

Saludos

**Comment by Hernan4444** [comment]
Puso haber sido un typo pero no es adicional. En CAAC si o si se busca que cambiar la clausura activa cambie el valor del predicado

Saludos :v:

**Comment by rasaffie** [comment]
@vmanriq Esta mención adicional es lo que diferencia a _CACC_ de _GACC_: si bien en _GACC_ la cláusula mayor debe ser activa (y por ende determinar el valor del predicado), puede ser que por los valores que se escojan para las cláusulas menores no se evalúen todos los valores del predicado cuando la cláusula mayor varíe.

De esta forma, en _CACC_ se da flexibilidad sobre los valores de las cláusulas menores siempre y cuando se prueben los valores posibles del predicado cuando la cláusula mayor varia (que es a lo que se refería @Hernan4444).

**Comment by shantifabri** [comment]
Hola, tengo una duda respecto a CACC. Para cumplir los dos requisitos de una cláusula mayor (que se evalúe como `True` y `False`, y lo mismo el predicado), ¿es necesario que para los dos casos las cláusulas menores tengan la misma valuación?

Si por ejemplo tengo el predicado `a and (b or c)`, y mi cláusula mayor es `a`, ¿podía ser que para el primer requisito yo tome `a=True, b=True, c=False` y que para el otro tome `a=False, b=False y c=True`? ¿o debiese ser para ámbos casos por ejemplo `b=True, c=False`?

Gracias!

**Comment by Hernan4444** [comment]
Hola,

No es necesario que tengan la misma valuación. CACC es más relajado en ese aspecto. Dejo a continaución una imagen que compara ambos y qué test acepta CACC VS RACC.

![image](https://user-images.githubusercontent.com/15641721/95247375-2c30bd00-07ec-11eb-9380-c50144bfcdfb.png)

fuente: https://www.cs.montana.edu/courses/se422/currentLectures/Ch3-1-2.pdf

Saludos :v:

**Comment by felipegarcia98** [comment]
@Hernan4444 disculpa lo tarde, pero, para un caso ``a ^ b ^ c`` en CACC, se puede considerar ``a`` como clausula mayor y al resto solo como clausulas menores, o hay que trabajar todas como una cláusula mayor en algún instante?

**Comment by Hernan4444** [comment]
@felipegarcia98 Es necesario trabajar con cada clausura como clausura mayor, es decir, primero asumir "a", luego "b" y luego "c".

Saludos :v:

**Comment by felipegarcia98** [comment]
gracias ❤
