### ISSUE TITLE
[Actividad 2] - Evaluación de las clausulas

### ISSUE THREAD

**Issue by Jiruiz2** [IIC3745-2020-2/syllabus#38]
Hola,

Para la actividad 2 tengo una duda sobre cuando se considera que una clausula fue evaluada. Por ejemplo, en el siguiente caso:

> if a and b:
> ---- bla bla bla

Si "a" se evalua como "false" entonces en teoría no se evaluaría "b", ya que el predicado completo sería false independiente de su valor. Sin embargo, tengo la duda si desde la teoría esto es así o se asume que se evaluaron todas las clausulas independiente de la clausula activa

Saludos

**Comment by Hernan4444** [comment]
Depende del coverage que estemos analizando. Si es ~CAAC~ RACC, lo importante es que bajo el mismo valor de las clausuras menores y cambiando únicamente el valor de la clausura activa, el valor de del predicado cambie. Esto implica que si deberás revisar que se "evalúen" las cosas. Por ejemplo con A and B. Alguien podría decir:

Clausura Activa A. "Con A = False, da lo mismo el valor de B, así que le pondré un False"
            A         B          predicado
TR1   False    False          False

pero ahora, para que predicado sea True haciendo que A sea True, también se ve obligado a cambiar el valor de B y ahí no respetó ~CAAC~RACC. Dado esto, B desde un inicio, como clausura menor, debió haber tomado el valor de True.

Ahora, con clause coverage (#35 ) basta con analizarlo teóricamente, no es necesario pensar en que se evalúe todo. Dado el mismo ejemplo de A and B, con A=True/B=True y A=False/B=False se suficiente aunque B en teoría jamas se evaluó False por el cortocircuito.

Finalmente, si nos podemos a pensar en Conditional Coverage, este si exige que se evalúe y por lo tanto, ahí si hay que pensar en los cortocircuitos al momendo de diseñar las pruebas.

Saludos :v:

Edit: se cambió CAAC por RACC

**Comment by Hernan4444** [comment]
Hola, 

En el comentario anterior me refería a RACC cuando puse que la clausura menor debe mantener su mismo valor siempre. Edité el comentario. En CACC se permite cambiar los valores de las menores tal que la mayor siga siendo activa y que el valor del predicado cambie.

Saludos :v:

**Comment by Jiruiz2** [comment]
Muchas gracias por la respuesta
