### ISSUE TITLE
Transferencias a otros usuarios

### ISSUE THREAD

**Issue by isidoravs** [IIC3745-2020-2/syllabus#4]
Hola!

Como grupo nos quedó la duda con respecto a las **transferencias en la aplicación**. Entendemos que la idea es permitir a los usuarios ordenar sus finanzas y que puedan registrar sus movimientos financieros de manera cómoda.

Considerando esto, nos imaginamos que _"registrar gastos o ingresos"_ consiste en agregar una entrada a los movimientos que el usuario quiere que queden registrados, sin efectivamente realizar una transacción o pago. Con esto, el _"saldo"_ que tiene el usuario es ficticio porque éste decide los débitos y créditos que va a registrar.

Entonces no nos queda claro cómo funcionarían las transferencias a otros usuarios de la aplicación. ¿Es una transferencia real que disminuye el saldo de uno y aumenta el del otro? No le vemos mucho sentido a esto, si consideramos que la aplicación es para ordenar finanzas y no para realizar transacciones reales, por lo que no sabemos si entendimos bien esa parte del enunciado o la idea final de la aplicación.

Feliz si nos pueden aclarar estas dudas, muchísimas gracias!

**Comment by Hernan4444** [comment]
Hola!

Efectivamente, la idea es que disminuye el saldo de uno y aumenta el del otro, si bien se aleja un poco del core de la app, esta funcionalidad está pensada para permitir una interacción entre usuarios de plataforma y agregar otros casos de test al proyecto. Damos completa libertad de ajustar esa funcionalidad  mientras la interacción entre usuarios mediante "transferencia" se cumpla. Por ejemplo, puede setear que la transferencia solo se ejecuta cuando uno indica que tiene una deuda o un préstamo con otro usuario de la plataforma.

Saludos :v:

**Comment by isidoravs** [comment]
Perfecto, gracias!
