### ISSUE TITLE
Formato de entrega

### ISSUE THREAD

**Issue by vbarreradg** [IIC3745-2020-2/syllabus#40]
Hola!

Para entregar la actividad hay que incluir el en .zip el test_helper? Y se deben poner los tests en la carpeta "tests" como estaba en el repo de ejemplo?

Gracias!

**Comment by Hernan4444** [comment]
Hola.

**Ideal si siguen ese formato** (agregar test_helper + poner todo en la carpeta tests), nos facilita más la corrección (ayudante feliz 👍 ), si no nosotros agregaremos esos archivos para ver la parte de simpleCov.

Saludos :v:
