### ISSUE TITLE
[A02] - Tests cases mínimo

### ISSUE THREAD

**Issue by Jiruiz2** [IIC3745-2020-2/syllabus#42]
Hola,

Tengo una duda sobre la definición de Test Cases mínimos que plantean, ya que dicen que estos se considerarán así si es que al eliminar alguno el nivel coverage de los TR disminuye. Sin embargo, si es que entre dos definiciones distintas para los test requirements se obtiene como resultado que en un caso son 5 TC mínimos, mientras que en otro son 6, pero cumpliendo la definición establecida, entonces, ambos serían correctos?

Saludos.

**Comment by rasaffie** [comment]
Una vez definido el criterio de cobertura bajo el cual diseñarás tus pruebas, de este se desprende un sólo conjunto de _test requirements_. Este conjunto puede variar según como definas tu criterio de cobertura, pero no habrán 2 definiciones para un mismo criterio. Luego, cada _test case_ de tu conjunto de pruebas debe probar por lo menos un _test requirement_ que el resto no pruebe, además de incluir el máximo de _tests requirements_ que sea posible en cada _test_.

**Comment by Hernan4444** [comment]
Complementando lo que dice el profesor, si bien esto implica encontrar la **mejor** combinación de TR por TC para minimizar la cantidad de test, igual vamos a flexibilizar esa exigencia. 

Por ejemplo, si alguien entrega 6 test y eran 5 el mínimo posible, igual estará bien, pero si alguien entrega 1 TC por cada TR cuando era claro que se podría haber reducido esa cantidad cambiando un poco algún TC para cubrir varios TR, entonces ahí se aplicará un descuento.

Saludos :v:
