### ISSUE TITLE
Duda cláusulas mayores en CACC

### ISSUE THREAD

**Issue by javierairarrazabal** [IIC3745-2020-2/syllabus#43]
Hola! Tengo una duda con respecto al Correlated active clause coverage.
 En clases se definió que para cada predicado y cada cláusula mayor se debe hacer que las cláusulas menores permitan que el predicado se haga verdadero o falso según la cláusula mayor. Esto significa que, por ejemplo, si tenemos A && B se debe elegir primero A cómo cláusula mayor y hacer los test necesarios, y luego elegir B como cláusula mayor, sumando los test correspondientes? O solo eligiendo A o B basta? 
Muchas Gracias!

**Comment by rasaffie** [comment]
Se debe realizar lo primero que dices: para cada cláusula del predicado se busca la combinación del resto de las cláusulas tal que la cláusula que se está analizando sea activa. Para cada una de estas combinaciones la cláusula activa que se está analizando se denomina mayor y el resto menores.

Si es que alguna cláusula no tiene ninguna combinación con las menores tal que esta sea activa para un predicado, entonces esa cláusula es redundante para el predicado y se puede eliminar.
