### ISSUE TITLE
Problema Test Controlador

### ISSUE THREAD

**Issue by jcechavarri** [IIC3745-2020-2/syllabus#44]
Hola!

Estoy teniendo un problema al testear el controlador de usuario, en específico el update. El test es:

![image](https://user-images.githubusercontent.com/42159312/95465321-5ea7fa80-0951-11eb-9107-dff5e6d956e2.png)

Y el error

![image](https://user-images.githubusercontent.com/42159312/95465393-77181500-0951-11eb-96c7-0577649eb701.png)

Me imagino que estoy pasando mal los parámetros pero no entiendo bien como debería ser 😢 

Muchas gracias!

**Comment by Hernan4444** [comment]
Hola, 

Creo que podría faltar el `render_views` dentro del `describe`
Fuente: https://stackoverflow.com/questions/24653543/expecting-index-but-rendering-with

Por otro lado, podrías hacer push del código en caso de no serlo, así podemos ver bien el controlador y todo el código para ayudar mejor

Saludos :v:

**Comment by rasaffie** [comment]
Sin revisar en detalle tu sintaxis, hay algo extraño en tu _test_: no puedes esperar que haga _render_ de `show` al mismo tiempo que se espera un _redirect_. 

Normalmente una acción exitosa de `update` hace un _redirect_ a la acción `show`, por lo que eso podría explicar que no se esté haciendo _render_ del `show` (que es lo que dice tu mensaje de error). Por otra parte, una acción fallida de `update` hace render de `edit` (no `show`), para mostrar el formulario con los errores correspondientes. Para probar ambos flujos debes realizar 2 _tests_ distintos.

Por último, como dice @Hernan4444, falta ver el código de tu aplicación para entender bien qué se está ejecutando. Sin embargo, más de un archivo puede afectar este comportamiento, por lo que debes tener claro el flujo completo que atraviesa una _request_ en tu aplicación. De todas formas, `render_views` no es el problema: está opción lo que hace es que se "dibujen" las vistas realmente, para así probar su contenido real. Lo que valida `render_template` es que se llame al `template`, pero no el contenido mismo del `template` porque este por defecto no se escribe, para así ahorrar tiempo de ejecución de los _tests_.

**Comment by jcechavarri** [comment]
@rasaffie @Hernan4444 

Entiendo que deben ser 2 *tests* (acción exitosa y fallida) pero no me queda claro como testear eso (pensé que si mis parámetros eran correctos me redireccionaría al `show`). Además, si le paso parámetros erróneos (nombre vacío, contraseñas incorrectas) igual se hace el `update` al atributo. Al pasar esto significa que tampoco voy a poder testear el `update` fallido ya que siempre se acepta mi `update`.

Bajo esta misma línea, ¿Cómo puedo testear que además de responder  con redirección llame a la vista correspondiente?

Dejo [acá](https://github.com/IIC3745-2020-2/grupo06/blob/21e3a692637a5b55c8f2152085678060ca535ca7/spec/controllers/users_controller_spec.rb#L55-L67) el link al test específico en nuestro repositorio.

Gracias de nuevo!

**Comment by Hernan4444** [comment]
Hola, sobre esta pregunta:

> Bajo esta misma línea, ¿Cómo puedo testear que además de responder con redirección llame a la vista correspondiente?

Una opción es hacer 2 test: uno done valida que se redireccione a la vista que quiere (por ejemplo `expect(response).to redirect_to user_path(user.id)` ) y otro test donde cargue esa vista y revisa que el template es el esperado. Pero lo que pides se puede hacer con otro tipo de tests más de integración, no en los unitarios para controladores. Sobre ese último tema, el profesor lo detallará mejor el fin de semana.

Saludos :v:

**Comment by jcechavarri** [comment]
@Hernan4444 

Gracias!

Todavía me queda la duda sobre el
> si le paso parámetros erróneos (nombre vacío, contraseñas incorrectas) igual se hace el update al atributo.

He intentado de varias formas y todavía no logro cubrir la parte del controlador que maneja los updates fallidos.

**Comment by rasaffie** [comment]
Hola Juan Carlos,

Sobre tu última pregunta, en tu controlador de `users` tu método `user_params` se ve así:
```ruby
def user_params
  params.require(:user).permit(:name, :last_name)
end
```

Por esta razón los únicos parámetros que se están considerando al realizar `@user.update(user_params)` son `name` y `last_name`. Puedes leer más sobre esto en la guía oficial de _Rails_ sobre [Strong Parameters](https://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters).

Además, en tu _test_ definiste tus parámetros como:
```ruby
params = { 
  "name"=>"new_name",
  "last_name"=>user.last_name,
  "email"=>user.email,
  "password"=>"newpassw",
  "password_confirmation"=>"newpassw",
  "current_password"=>user.password
}
```
los cuales no están dentro de un objeto `user` como lo definen tus `user_params`. Por otra parte, utilizas la [notación implicita de RSpec](https://relishapp.com/rspec/rspec-core/v/3-9/docs/subject/one-liner-syntax#implicit-subject) `is_expected.to` que infiere el `subject`, pero por como organizaste tus _tests_ lo debe estar haciendo de mala manera. Te recomiendo que [definas un `subject` explícitamente](https://relishapp.com/rspec/rspec-core/v/3-9/docs/subject/one-liner-syntax#explicit-subject) o que llames a la acción directamente como en tu _test_ de `destroy`:
```ruby
expect { delete :destroy, params: { id: user } }.to change { User.count }.by(-1)
```
Cuéntame si aún tienes dudas, saludos,
