### ISSUE TITLE
Duda con tipos de cuenta 

### ISSUE THREAD

**Issue by camichavez** [IIC3745-2020-2/syllabus#45]
Hola! me tiene confundida un poco lo de los saldos liquidados con los tipos de cuenta. Ya leí la issue donde explicaban que eran estos saldos, pero como uno puede tener distintos tipos de cuentas me confunde. En la realidad por ejemplo si uno tiene una cuenta corriente y tiene tarjeta de crédito y débito, ocupo el saldo de mi tarjeta de débito para pagar mis deudas en la tarjeta de crédito. Pero en estos casos, entiendo que uno escoge desde la cuenta que uno decide hacer el gasto o la deuda, etc. entonces mi primera duda es cómo voy a tener una deuda en la tarjeta de débito si en teoría cuando uno paga con esa tarjeta automáticamente se descuenta mi plata? y en caso de que no tenga saldo, esto podría (por ejemplo) pasar a mi tarjeta de crédito pero a cuál de todas si puedo tener varias de esas?  o en teoría deberíamos restringir a que las deudas no se hagan con la tarjeta de débito?
Y respecto a si pago un saldo que debía en una tarjeta de crédito, no entiendo de donde estoy descontando esa plata, de alguna de mis tarjetas de débito, yo la escojo? o es algo más ficticio tipo tener un formulario donde yo ingrese "quiero pagar 4.000 de mi deuda de 10.000" entonces ahora el saldo liquidado pasa a ser 4.000 y mi saldo no liquidado pasa a ser 6.000, y no se descuenta plata de ninguna parte?
O una transferencia entre mis cuentas desde una cuenta de débito a una de crédito cuenta como que estoy pagando mi deuda? 
Otra cosa que no entiendo es en que influye la cuenta corriente, en qué caso estaría involucrada esta?  
Sorry tantas dudas y si no se entiende me dicen para intentar explicarme mejor. Quizás esto hilando muuy fino pero con tanta confusión me está costando implementarlo :( graciaas!

**Comment by iaacosta** [comment]
Hola @Cschavez!

Las dudas que planteas son muy buenas, cuesta un poco adaptarse al concepto. Escribiré un par de puntos aclaratorios y luego responderé tus preguntas:

1. **Saldo liquidado**: transacción pagada. **Saldo no liquidado**: transacción con compromiso de pago.
2. En una cuenta corriente / de débito hace un poco de ruido el saldo no liquidado, porque todo movimiento se puede tomar como una transacción pagada.
3. En la issue voy a hablar de **deudas** como que _le debo dinero a alguien_ y **préstamos** como que _me deben dinero_

Ahora, para ir respondiendo tus preguntas:

- **¿Cómo puedo tener una deuda en una cuenta de débito / corriente?** Depende de cómo manipules las deudas en la interna de la aplicación. Para explicarlo mejor, supongamos fuiste a un bar / restaurante / completos / sopaipillas con tres de tus amig@s y el total de la cuenta fue $12.000 ($3.000 c/u). En caso de que un@ del grupo pague todo, tú le debes $3.000. Hay varias alternativas de como manejar esto, se me ocurren dos:

   1. Entras a la plataforma e indicas que debes $3.000 y que la pagarás con tu cuenta de débito algún día.
   2. Entras a la plataforma e indicas que debes $3.000 sin indicar cuenta.

   En la i. eliges una cuenta y existe un saldo no liquidado de -$3.000 en tu cuenta de débito. En la ii. hay un saldo no liquidado de -$3.000 sin cuenta asociada. **Ambas formas son válidas**.

   Supongamos ahora tú eres la que paga la totalidad de la cuenta. Se genera un préstamo de $9.000 (o tres préstamos de $3.000). También tienes varias alternativas para manejar esto:
  
   1. Entras a la plataforma e indicas que te deben $9.000 y te pagarán en tu cuenta de débito algún día.
   2. Entras a la plataforma e indicas que te deben $9.000 sin indicar cuenta.

   En la primera, se genera un saldo no liquidado de $9.000 en tu cuenta de débito, y en la segunda hay un saldo no liquidado de $9.000 sin cuenta asociada. Nuevamente, **ambas son válidas**.

   A lo que voy con esto, es que sí: puede ser que tus cuentas de débito y corrientes no tengan saldos no liquidados, pero **deben manejar los saldos no liquidados de las deudas y préstamos en alguna otra parte**.
- **¿Cómo se paga mi saldo de tarjeta de crédito?** Creo hay una confusión entre el concepto de pagar y liquidar. Liquidar es hacer notar que un saldo en una cuenta es algo que ya existe como cobro. Pagar una tarjeta de crédito es transferir desde otra cuenta. **Si se liquida un saldo, no es que desaparezca, sino que pasa a ser saldo liquidado**.  Para ilustrarlo con un ejemplo
   1. **Pago $20.000 con mi tarjeta de crédito** - saldo no liquidado pasa a ser -$20.000.
   2. **Llega el momento en que mi banco me cobra los pagos de este mes y lo indico en la plataforma** - saldo no liquidado pasa a ser $0 y el saldo liquidado pasa a ser -$20.000
   3. **Pago lo que debo de mi tarjeta de crédito** - transfiero $20.000 desde mi cuenta de débito a mi cuenta de crédito. El saldo liquidado de crédito pasa a ser $0.
- **¿Cómo influye la cuenta corriente?** Es simplemente una variante de la de débito con más libertades. No tiene un cambio radical como las tarjetas de crédito.

Para cerrar un poco, esto que te planteo son alternativas a como implementarlo, pero la idea de la aplicación es que puedan testear. Si creen que hay una mejor forma de implementar esto, se lo pueden plantear a su ayudante y discutirlo en la interna.

Espero igual que esto haya aclarado en algo tus dudas, quedo atento por cualquier otra que pueda surgir.

Saludos!
