### ISSUE TITLE
Erro PG::Connection

### ISSUE THREAD

**Issue by tamaralues** [IIC3745-2020-2/syllabus#46]
Hola! He estado teniendo este error para poder correr el repositorio para el proyecto, probé varias cosas pero no logro solucionarlo, saben a que se podría deber??
<img width="654" alt="Screen Shot 2020-10-13 at 09 05 33" src="https://user-images.githubusercontent.com/29900907/95859407-f54f2f80-0d34-11eb-8672-c2f88b499781.png">

**Comment by iaacosta** [comment]
Hola @tamaralues

¿Estás corriendo el proyecto con Docker o de manera local? El repositorio está configurado para funcionar con Docker, a menos que tu grupo o tú hayan hecho una configuración adicional.

Por lo que veo del error, Ruby on Rails está tratando de conectarse a `localhost` y al puerto `32775`, cuándo la idea es que conecte a el hostname `postgres` con el puerto `5432` en caso de usar Docker.

Te pido también mostrar el archivo `config/database.yml` y el `docker-compose.yml` si es que lo estás usando.

¡Quedo atento!

**Comment by tamaralues** [comment]
<img width="783" alt="Screen Shot 2020-10-13 at 09 39 04" src="https://user-images.githubusercontent.com/29900907/95861527-f170dc80-0d37-11eb-89aa-6fe08cd73abd.png">
<img width="564" alt="Screen Shot 2020-10-13 at 09 38 49" src="https://user-images.githubusercontent.com/29900907/95861538-f5046380-0d37-11eb-9cd1-5933ddb2bc2e.png">

Siisis, pero es raro porque esta configurado al puerto correcto, probé borrando los contendores de docker antiguos pero no es eso al al parecer

**Comment by rasaffie** [comment]
No sé por qué puede estar fallando o por qué aparece el puerto 32775 si es que tienes configurado el puerto 5432. Revisando lo que aparece en [este enlace](https://stackoverflow.com/questions/19828385/pgconnectionbad-could-not-connect-to-server-connection-refused) prueba lo siguiente:

* En la carpeta del proyecto, luego de ejecutar `docker-compose up -d` ejecuta `docker-compose ps` para ver el estado de los contenedores. Si el contenedor de la base de datos no dice `Up` es porque no estás corriendo la base de datos. Puedes ver los logs del contenedor X con `docker-compose logs X`.
* Revisa si ya tienes una instancia de Postgres corriendo en tu computador (puede ser otro contenedor de docker o localmente). Para listar todos los contenedores de docker puedes hacer `docker ps`.
* Revisa según tu sistema operativo si tienes un archivo `.pid` y borralo.
* Elimina los volúmenes además de los contenedores con `docker system prune -a --volumes`. Tienes que detener los contenedores con `docker-compose down` para que estos se eliminen.

**Comment by tamaralues** [comment]
Solucionado! Muchas gracias, me funciono con el de volumes, tenía un proyecto de otra ramo que esta generando el error
