### ISSUE TITLE
[AC04] - Problema que ocurre en Fintual

### ISSUE THREAD

**Issue by Jiruiz2** [IIC3745-2020-2/syllabus#47]
Hola,

Tengo una duda sobre cual es la causa del problema que se presenta en la actividad 4, ya que se habla de un problema en el pago de las cuentas, sin embargo, al final se señala que una URL puede haber quedado asociada al HTML del error, por lo que puede haber sido todo un problema de ruteo inicialmente.
![image](https://user-images.githubusercontent.com/26437497/97816747-075a2900-1c76-11eb-800e-31ee60b88fb5.png)

Saludos

**Comment by rasaffie** [comment]
Hola Javier,

Parte del ejercicio es que propongan la causa que les parezca más razonable en base a lo que se pueda desprender de la conversación. En este sentido, si la causa que proponen va alineada con la conversación y se basa en supuestos razonables dentro del contexto del ejercicio, entonces podría haber más de una respuesta correcta. De todas formas, todo lo que respondan debe tener algún fundamento en la conversación, ya que lo que se aleje considerablemente de esta no se considerará correcto.
