### ISSUE TITLE
Error con factory bot al correr los test

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC3745-2020-2/syllabus#48]
Hola!
Sucede que los test estaban corriendo bien, y probando algunas cosas creo que me eché algo :grimacing: y ahora me sale este error:

```
Failure/Error: @user = FactoryBot.create( :user )
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
```
Pero, estamos usando el siguiente código para la factory:

```rb
FactoryBot.define do
  # Para atributos que no se pueden repetir
  sequence :email do |n|
    "person#{n}@walletest.cl"
  end

  # Uso: FactoryBot.create( :user, traits: [:admin] )
  factory :user do
    trait :admin do
      is_admin { true }
    end
    name { 'Name' }
    lastname { 'LastName' }
    rut { '11.111.111-1' }
    email { generate :email }
    password { 'aaaaaa' }
  end
end
```
Y obviamente antes corrí mil veces los test y todo funcionaba bien y después algo debo haber hecho que dejó de funcionar, volví al código atrás cuando todo funcionaba y me sigue tirando el error. 

Busqué el error en google, pero hablan quizás de una gema para limpiar la bd, pero no sé si es lo correcto.

Ayuda por favor :cry:

**Comment by rasaffie** [comment]
Hola,

Pienso que el problema puede ser la notación que usas para generar la secuencia de `email` (porque nunca había visto esa notación). Ve si usando la secuencia directamente dentro de la factory de `user` (como [en este ejemplo](https://github.com/IIC3745-2020-2/example/blob/example/capybara/spec/factories/user.rb#L7)) se soluciona tu problema.

De no ser así, entonces puede ser un problema con los datos de pruebas. Como comentas, una opción es que no se esté limpiando correctamente la base de datos después de cada _test_. Pienso que la forma más fácil de comprobar este supuesto es borrando la base de datos de pruebas completamente y creandola nuevamente, con `rails db:drop` y `rails db:create db:schema:load` (tienes que especificar `RAILS_ENV=test` si no quieres perder los datos de `development`). Luego, tienes que correr solamente el _test_ que falla (para evitar que otros _tests_ poblen la base de datos que podría tener problemas de limpieza), y si este aprueba, entonces el problema es lo que comentas.

Otra opción es que para el _test_ que te falla crees "a mano" el mismo usuario con correo duplicado. Esto puede estar oculto a través de `before` anidados. Sin embargo esta opción es extraña porque si estás haciendo _checkout_ a un _commit_ que antes funcionaba no debería ser este el problema. 

Una última opción que se me ocurre es que estés usando la funcionalidad de [_fixtures_ de _RoR_](https://guides.rubyonrails.org/testing.html#the-low-down-on-fixtures). No he mencionado este concepto en clases pero resumidamente los datos que se crean a través de esta forma se definen como el "estado inicial" para cada _test_: luego de que se ejecute cada test se hace _rollback_ a los datos que se definieron en las _fixtures_. La idea de esto es ganar tiempo al ejecutar los _tests_ porque los datos definidos en las _fixtures_ se crean una sola al inicio, y entre tests se realiza un _rollback_ solamente, lo que es más rápido que crear y borrar registros en la base de datos entre cada _test_. Por lo tanto, si es que en las _fixtures_ definiste un usuario, y luego en los tests tratas de crearlo nuevamente entonces fallará por correo duplicado.

También puedes probar si un compañero tuyo de grupo también tiene este error al ejecutar los tests. De esta forma podrás ver si el problema es por una configuración de tu computador o un error de la aplicación.

Cuéntame si alguna de estas opciones te encamina a solucionar el problema. De lo contrario tendrías que entregar más detalle como el _test_ en particular que te falla en qué _commit_, y un _commit_ en que estés completamente segura que funcionaba, para así poder comparar todos los cambios que se hicieron entremedio y ver si hay alguna explicación a nivel de código.

**Comment by ValentinaAlvarezG** [comment]
Buenísima! Gracias, me sirvió dropear la bd, algún condoro me debo haber mandado. Igual, para entender un poco mejor como funciona esto, cada vez que corro todos los test se agregan entradas a la bd? Y eso no se borra a menos que la dropee manualmente?

**Comment by rasaffie** [comment]
Depende como configures tu ambiente de pruebas qué pasará con los datos entre cada _test_. Por ejemplo, RSpec por defecto configura que cada _test_ se ejecute dentro de una transacción, para que así las modificaciones a los datos entre _tests_ sean independientes. En [esta sección](https://relishapp.com/rspec/rspec-rails/docs/transactions) de la documentación de RSpec puedes leer más sobre esto.

Por otra parte, Cucumber no tiene una política incluida para esto, [por lo que recomiendan](https://github.com/cucumber/cucumber-rails#installation) incluir `database_cleaner` al instalar la gema en _RoR_.

Sospecho que tu problema se debía a que la base de datos de _tests_ tenía datos antes de que ejecutaras los _tests_ (quizás los agregaste sin darte cuenta), por lo que estos no se borraban entre las ejecuciones de los _tests_.

**Comment by ValentinaAlvarezG** [comment]
Buena! Muchas gracias
