### ISSUE TITLE
Test con Capybara no encuentra elemento css - ejemplo clase create user

### ISSUE THREAD

**Issue by B-Dominguez** [IIC3745-2020-2/syllabus#49]
Hola! Estoy implementando algo equivalente al ejemplo mostrado en clases para create_user. Estoy teniendo el problema de que capybara no encuentra el elemento css, aunque sí encuentra el texto:
![image](https://user-images.githubusercontent.com/26129405/98398046-10187980-203f-11eb-9a6c-a3fe1ff9f95f.png)

Al replicar los pasos del test en el navegador y usar el inspector, puedo ver que el selector sí existe:
![image](https://user-images.githubusercontent.com/26129405/98397594-591bfe00-203e-11eb-8bb1-d60046d37eef.png)

Este es el segmento de código:
![image](https://user-images.githubusercontent.com/26129405/98397860-c596fd00-203e-11eb-928d-b64520d7565d.png)

Alguna idea de qué podría estar fallando? En internet no encontré mucho

**Comment by rasaffie** [comment]
Hola,

Si te fijas en el detalle del error de la prueba el problema no es que no encuentra el elemento HTML, sino que el texto no es el mismo que espera. La diferencia que hay es que uno dice `this client` y el otro dice `this user`.

Este ejemplo demuestra la importancia de que los _tests_ tengan nombres y errores descriptivos, para que cuando fallen sea más inmediato entender por qué.

Saludos,

**Comment by B-Dominguez** [comment]
Toda la razón profe, muchas gracias!

**Comment by Jiruiz2** [comment]
Me quiero sumar a la duda porque tengo un problema similar.

Este es el código de mi test, donde @transaction se define en el before do mediante una factory (que funciona bien, ya que el test del new se supera correctamente)

![image](https://user-images.githubusercontent.com/26437497/98869874-2d8b8000-2451-11eb-8bcb-bb7860cabd32.png)

El html-css de la vista es el siguiente:

![image](https://user-images.githubusercontent.com/26437497/98870136-a094f680-2451-11eb-8e90-91d83ae8009a.png)

Y el error que me entrega es el siguiente:
![image](https://user-images.githubusercontent.com/26437497/98870222-c0c4b580-2451-11eb-9847-183266c354a3.png)

**Comment by rasaffie** [comment]
Pienso que el error se debe a la definición de `@transaction`, por lo que no se ingresa a la vista que esperas, pero es difícil estar seguro sin mayor contexto. Por otra parte, no entiendo a qué te refieres con que funciona para el `new` ya que para esa acción no se necesita tener un registro en la base de datos.

Te recomiendo que dentro del _test_ hagas _print_ (o uses _byebug_) para ver los valores de las variables `@transaction` y `page`. También puede ser más fácil usar los _helpers_ de rutas más que escribirla con _string interpolation_: `visit edit_transaction_path(@transaction)`

**Comment by Jiruiz2** [comment]
Me sirvió el consejo de printear el html de page, no se me había ocurrido. El problema que tengo ahora es que no logra encontrar el current_user dentro del form, por lo que el test falla y se cae.
Actualmente tengo la siguiente configuración en mi rails_helper.rb para usar devise:
![image](https://user-images.githubusercontent.com/26437497/98886436-d5657580-2472-11eb-90ab-a5355dfca0c7.png)

Y hago el log in de la siguiente manera:
![image](https://user-images.githubusercontent.com/26437497/98886521-05147d80-2473-11eb-9cc3-cf6d875ce71f.png)

El error es el siguiente:
![image](https://user-images.githubusercontent.com/26437497/98886698-515fbd80-2473-11eb-8cd0-342d78ada612.png)

Notas: 
- Estos tests están en la carpeta features.
- He probado con sign_in y me da error por env
- Factory crea bien a los usuarios, ya que se ha probado en otros tests y funcionan bien
- El problema es definitivamente el current_user, probé hardcodeando en la vista cambiando solo eso y funcionó

### **Edit**
Cambié before :all por before :each y funcionó
