### ISSUE TITLE
Testing en el front

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC3745-2020-2/syllabus#5]
Hola! 
Con mi grupo nos quedaron un par de dudas sobre que tan exigente va a ser sobre el test de front. En el enunciado de la entrega 1 dice "Test de vistas", pero nada más. 

Si agregamos un framework de fonrt (Vue), es necesario agregarle test a los componentes? La misma duda sobre las vistas en Rails.

Gracias!

**Comment by rasaffie** [comment]
Hola,

La idea es que todos los grupos utilicen el mismo _stack_ de desarrollo. En este sentido, no deben utilizar _frameworks_ para _front-end_ (como _react_, _vue_ o _angular_) porque agregarán más complejidad de la que queremos abarcar con el proyecto. Por esto, deben utilizar ERB como se explica en [la guía oficial de Rails](https://guides.rubyonrails.org/action_view_overview.html#erb), además de utilizar [erb-lint](https://github.com/Shopify/erb-lint).

Sobre los _tests_ de vistas, veremos más detalles sobre lo que se espera en una próxima clase antes de la fecha de la entrega, pero por el momento puedes encontrar más detalles en [la guía oficial de Rails](https://guides.rubyonrails.org/testing.html#testing-views).

**Comment by rasaffie** [comment]
Como aclaración: el segundo enlace de mi respuesta anterior se refiere al tipo de cosas que se pueden probar en las vistas, pero esa sintaxis no nos servirá para el proyecto porque está hecha con Minitest. [En la documentación de RSpec](https://relishapp.com/rspec/rspec-rails/v/4-0/docs/view-specs/view-spec) pueden encontrar ejemplos de _tests_ de vistas.

**Comment by fdominguezclaro** [comment]
Como grupo creemos que el uso de _frameworks_ de front pueden incluso simplificar el trabajo a realizar. Existen librerías con muchos componentes que nos pueden ser útiles y permiten un rápido desarrollo. La idea es hacer uso de estos pero de la forma más simple posible. Sin usar _Vuex_ ni nada para manejar estados.

Existe la posibilidad de agregar un _framework_ a nuestro riesgo?

**Comment by fdominguezclaro** [comment]
@rasaffie lo etiqueto por si se le pasó el comentario, para poder empezar ya con el proyecto. 
Gracias!

**Comment by rasaffie** [comment]
Hola Felipe,

Discutí este tema con el equipo docente y decidimos reafirmar nuestra postura de que se utilice solamente ERB para el _front-end_. Si bien entiendo que puede ser interesante aprovechar el proyecto para ganar experiencia con otras tecnologías, esta decisión se basa en que:

* el año pasado permití que los alumnos utilizaran distintos _frameworks_ de _front-end_, lo que fue una mala experiencia ya que generó trabajo extra de configuración e investigación.
* si bien con la ayuda de componentes pre-hechos las vistas de la aplicación pueden quedar "_mejores_", este no es el objetivo principal del proyecto, el cual es experimentar una experiencia de desarrollo de _software_ enfocada en la calidad del proceso.
* no es viable que los ayudantes sean expertos y puedan corregir distintos _frameworks_, por lo que debemos definir un stack común de herramientas para todos los grupos.

Espero que estos argumentos te parezcan razonables ya que no se modificará esta exigencia.

Saludos!

**Comment by pdesolminihac** [comment]
Hola!

Pensando en que en el thread dicen que las vistas van a ser en ERB podemos incluir cosas más dinámicas con JS pero sin un framework de Front?

**Comment by fdominguezclaro** [comment]
Ok perfecto! 
Gracias por el tiempo de explicar por qué no lo podemos usar 👍 

Saludos!

**Comment by rasaffie** [comment]
> Hola!
> 
> Pensando en que en el thread dicen que las vistas van a ser en ERB podemos incluir cosas más dinámicas con JS pero sin un framework de Front?

Mientras puedan realizar pruebas sobre los elementos HTML de las vistas generadas con ERB, no hay restricciones sobre las dependencias que agreguen para mejorar el estilo y comportamiento de su aplicación. En este sentido, no les pediremos que sus pruebas de _front-end_ sean exhaustivas ni tampoco que diseñen pruebas de bajo nivel sobre su código en JS.
