### ISSUE TITLE
Test con Capybara y rubocop

### ISSUE THREAD

**Issue by kenzoak** [IIC3745-2020-2/syllabus#51]
Al realizar los test con capybara basándome en el código de ejemplo del profesor, estoy enfrentando algunos problemas con rubocop. En particular:

- RSpec/ExampleLength: Example has too many lines: RSpec/ExampleLength: Example has too many lines
    
  En este caso el problema es por el largo del test. Debería tratar de acotarlo a lo predeterminado (5 lineas) o debería ajustar esta restricción en rubocop?

-  RSpec/MultipleExpectations: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/MultipleExpectations

   En este caso, me limita el número de 'expect().to....' en cada test. Nuevamente me pregunto si debo dejarlo en lo predeterminado (1 por test) o puedo ajustar esto en rubocop, ya que en el código de ejemplo el profesor usa hasta 4 en un mismo test. 

Muchas gracias

**Comment by iaacosta** [comment]
Hola @kenzoak 

El tema de las reglas de `rubocop` (y de cualquier guía de estilos) es bien subjetivo. Por un lado la idea es que tod@s en el equipo de desarrollo sigan un mismo estilo de código, pero también se limitan a buenas prácticas en ciertos casos.

**Comment by iaacosta** [comment]
Hola @kenzoak

El tema de las reglas de `rubocop` (y de cualquier guía de estilos) es bien subjetivo. Por un lado la idea es que tod@s en el equipo de desarrollo sigan un mismo estilo de código, pero que también se limitan a reglas que obligan buenas prácticas. Las dos restricciones que mencionan no son la excepción e incluso son harto más a criterio del equipo que otras.

Para el proyecto está bien si les cambian las exigencias dentro de un rango razonable. Por ejemplo, `RSpec/MultipleExpectations` tiene un atributo `Max` que está configurado en `1`, aumentarlo a `5` estaría bien pero `100` ya es dudoso. Similar para `RSpec/ExampleLength`, es razonable aumentarlo a `10` o `15` lineas pero no `100`.

Saludos!

**Comment by kenzoak** [comment]
Hola, 

Gracias por la respuesta, me quedó claro
