### ISSUE TITLE
Estructura Archivos Actividad 5

### ISSUE THREAD

**Issue by pepina-dev** [IIC3745-2020-2/syllabus#52]
Hola!  No me queda claro si tenemos que borrar los  archivos que no sean las carpetas app, spec e integrantes.md  o si se pueden dejar en el zip. Saludos!

**Comment by iaacosta** [comment]
Hola @MariaJosefinaAlliende! 

Si, la idea es borrar los archivos que no salen explícitos en el enunciado. El zip sólo debe contener `app/*`, `spec/dcc_burger_spec.rb` e `integrantes.md`.

Avísame si sigues teniendo dudas 😃
Saludos

**Comment by pepina-dev** [comment]
Buenísimo, gracias por la aclaración!
