### ISSUE TITLE
Problema al ejecutar comando mutant

### ISSUE THREAD

**Issue by Jiruiz2** [IIC3745-2020-2/syllabus#53]
Hola,

El comando de docker no me funciona por un error de formato:

![image](https://user-images.githubusercontent.com/26437497/99315397-5b9e0500-2841-11eb-832d-5fbd1388afcb.png)

**Edit **

Logré solucionar el problema agregando comillas de la siguiente manera:
* `docker run -it --rm --name a05-base -v "$(pwd):/tester" iic3745-2020-2/a05-base`

**Comment by iaacosta** [comment]
Hola @Jiruiz2!

No me ubico mucho en Windows, por lo que no sabría decirte porque se da el error al correrlo localmente. ¿Tienes la versión 2.6.6 de `ruby` o alguna otra?

Respecto a Docker, los comandos usan ciertos parámetros _UNIX-like_ como el `$(pwd)` para montar el volumen. El equivalente en Windows según vi debería ser `${PWD}`, es decir:

```
docker run -it --rm --name a05-base -v "${PWD}:/tester" iic3745-2020-2/a05-base
```

Para que lo pruebes y veas que eso te corre. 
Saludos!

**EDIT**: Vi tu edit, qué bueno que eso te haya servido!
