### ISSUE TITLE
"== vs eql?" en mutant

### ISSUE THREAD

**Issue by Jiruiz2** [IIC3745-2020-2/syllabus#54]
Hola,

Estoy teniendo el siguiente problema con mutant 
![image](https://user-images.githubusercontent.com/26437497/99330580-6dda6c00-285e-11eb-8b37-d0abb86596b2.png)

En el ejemplo que nos dieron hablan de ese tema y lo solucionan cambiando todos los == por eql?, pero quería confirmar si ese cambio está permitido en esta actividad, tomando en cuenta que no debemos cambiar las condiciones
![image](https://user-images.githubusercontent.com/26437497/99331464-b003ad80-285e-11eb-9788-bc8512442dec.png)

**Comment by iaacosta** [comment]
Hola @Jiruiz2!

Si el cambio no significa una modificación significativa en la lógica del programa, si se puede hacer. 

El el artículo se dice que `eql?` es una operación que importa más cuándo estamos utilizando `Hash`s, pero piénsalo en términos prácticos de la actividad (`string`s), ¿el `==` abarca algún caso que `eql?` no abarque?

Si la respuesta es si, entonces falta un _test case_ que evite que `mutant` logré hacer pasar los tests aún con esta mutación. Si la respuesta es no, el cambio entre operadores es válido.

Avísame si te quedan dudas
Saludos!

**Comment by tamaralues** [comment]
Hola!
disculpa la hora, esque revisé recien esta issue, en el caso de ===  estaría dentro de lo permitido?

**Comment by iaacosta** [comment]
Hola @tamaralues!

Aplica el mismo razonamiento: ¿el cambio de `==` a `===` omite un caso borde? Si es que si, entonces no es válido. Si es que no, entonces si lo es.

Saludos
