### ISSUE TITLE
docker: invalid reference format: repository name must be lowercase. ACTIVIDAD 5

### ISSUE THREAD

**Issue by ftrejoc** [IIC3745-2020-2/syllabus#55]
Hola!
E estado de correr docker reiteradas veces y no he podido solucionar este problema para la actividad!

**Comment by iaacosta** [comment]
Hola @ftrejoc!

¿Podrías dar más detalles acerca del error que tienes? ¿Qué sistema operativo usas? Si es Windows, ¿usas WSL 1, 2 o ninguno? ¿Has probado corriéndolo de manera local?

Saludos

**Comment by ftrejoc** [comment]
Uso MacOS. Al correr el último comando para correr docker. Corriendolo de manera local, mutant no me esta agarrando los cambios que estoy haciendo en el codigo

**Comment by iaacosta** [comment]
El problema parece ser que hay espacios en tu _working directory_ (puedes verificarlo corriendo `pwd` en la terminal, es algo similar a la issue #53). Intenta correr este comando:

```
docker run -it --rm --name a05-base -v "$(pwd):/tester" iic3745-2020-2/a05-base
```

Saludos!

**Comment by ftrejoc** [comment]
Perfecto, lo intentare muchas gracias!
