### ISSUE TITLE
Problemas al partir actividad

### ISSUE THREAD

**Issue by behrmann97** [IIC3745-2020-2/syllabus#56]
Hola, perdón por lo tarde de esta issue pero no tuve tiempo para partir antes. Clone el repositorio y lo inicié con docker tal y como dice el readme y me conecté a su bash, pero al hacer rspec me dice 0 examples y si corro mutate dice command not found. No estoy seguro qué se puede hacer al respecto, ya que el build no me tira ningun error.

**Comment by iaacosta** [comment]
Hola @behrmann97!

Para entender mejor tu problema, si corres `ls` dentro del contenedor, ¿qué output tienes?

¿Que sistema operativo usas? Si es Windows, ¿usas WSL 1, 2 o ninguno?

Saludos

**Comment by behrmann97** [comment]
Hola, uso wsl2, pero ya logré usar el rspec. Sin embargo, ahora con mutate me dice "bad interpreter: no such file or directory".

**Comment by iaacosta** [comment]
¿Te funciona si corres directamente `mutant`? Intenta con

```
bundle exec mutant -I . --use rspec 'DCCBurger'
```

**Comment by behrmann97** [comment]
Sí! Muchas gracias!

**Comment by behrmann97** [comment]
Hola, ¿es sólo ese comando? Al correrlo (después de varios cambios) me tira lo siguiente:
![image](https://user-images.githubusercontent.com/26407766/99464673-6dea7280-2917-11eb-9aeb-53e51c98bca8.png)
Que dice 100% coverage, pero 32.61% de rspec. No sé si está bien o hay que agregar nuevos test o correr otro comando.

**Comment by iaacosta** [comment]
Hola @behrmann97!

El coverage de RSpec no se evalúa en esta entrega, así que no te preocupes por eso.

No obstante, dado que `mutant` refuerza la batería de pruebas, debería seguir en 100% de coverage (que lo obtienes al correr RSpec a mano)

Saludos

**Comment by behrmann97** [comment]
Efectivamente tenemos 100% al correr rspec a mano :). Muchas gracias!
