### ISSUE TITLE
Descripción grupo de muestra

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC3745-2020-2/syllabus#57]
Hola! para las pruebas de usuarios de la entrega 4, dice que tenemos que "Describir grupo de muestra con el cual se realizaron las pruebas". No entiendo muy bien que se espera en esta parte, tenemos que describir a cada usuario? onda nombre, edad, ocupación, esa clase de cosas? 

Gracias! c:

**Comment by rasaffie** [comment]
Claro, la idea es describir a los usuarios en base a las características que sean relevantes para la aplicación y las pruebas. De esta forma se podría interpretar de mejor manera los resultados al relacionarlos con esa información. Los ejemplos que nombras están bien pero pueden haber más características que sean interesantes, como por ejemplo nivel de estudios o si es usuario de otra plataforma similar o de un banco.

**Comment by ValentinaAlvarezG** [comment]
Bacán! gracias 😄
