### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by stmorales** [IIC3745-2020-2/syllabus#58]
Hola

Los dashboards deben ser por cada cuenta específica o tomando en cuenta todas las cuentas que existen de un usuario?

Muchas gracias!

**Comment by Hernan4444** [comment]
Hola,

Lo esperado es que sea por cada cuenta, pero puede variar si para su proyecto creen que queda mejor con un dashboard que considera todas las cuentas. 

Saludos :v:

**Comment by stmorales** [comment]
´Gracias!!
