### ISSUE TITLE
Tests de usabilidad

### ISSUE THREAD

**Issue by fnquinteros** [IIC3745-2020-2/syllabus#59]
Hola! Quería saber si todas las cosas enumeradas al principio del documento [pruebas-de-usuario.md](https://github.com/IIC3745-2020-2/syllabus/blob/master/proyecto/entrega4/pruebas-de-usuarios.md), en la parte de "Definir escenarios o tareas...", son requeridas o si son sugerencias. He buscado algunos métodos para evaluar la usabilidad de una app y quisiera saber si me inclino por seguir estas metodologías o por cumplir con todo lo que piden en el enunciado.

**EDIT:** Cabe mencionar que para hacer la rúbrica de testeo, seguí metodologías que piden hacer más o menos lo mismo que se pide en el enunciado, pero no exactamente eso, y permite obtener un resultado numérico con el cual medir efectividad, eficiencia y satisfacción. Me parece que es un método bastante completo y pienso que se perdería mucho si sigo las instrucciones del enunciado al pie de la letra en vez de realizar los tests según estos métodos que encontré.

 Gracias!

**Comment by rasaffie** [comment]
Hola,

Si bien en el enunciado se definen requisitos a cumpir para estandarizar las entregas, no tengo problemas en que utilices otras metodologías siempre y cuando se respete el espíritu de las pruebas de usuario. Dicho esto, en tu entrega deberás agregar referencias al material que utilices y justificar brevemente qué ventajas tiene esa metodología por sobre lo propuesto en el enunciado.

Saludos,
