### ISSUE TITLE
Formato entrega AC01

### ISSUE THREAD

**Issue by fnquinteros** [IIC3745-2020-2/syllabus#6]
Hola!

El formato de entrega para la actividad cuál será? y cómo se entregará? (canvas, correo, etc?).

Saludos

**Comment by fnquinteros** [comment]
Y en particular la parte A debe ser respondida como si programara casos de prueba en Rails? o una descripción escrita solamente?

**Comment by rasaffie** [comment]
> Hola!
> 
> El formato de entrega para la actividad cuál será? y cómo se entregará? (canvas, correo, etc?).
> 
> Saludos

Durante los próximos días detallaremos el formato de entrega a través de un anuncio.

> Y en particular la parte A debe ser respondida como si programara casos de prueba en Rails? o una descripción escrita solamente?

Para la parte A no se espera que implementen código, solamente que diseñen y detallen los casos de prueba.

**Comment by rasaffie** [comment]
Publiqué un anuncio sobre esto, y la _issue_ https://github.com/IIC3745-2020-2/syllabus/issues/13 responde en más detalle a la pregunta sobre la parte A.

**Comment by fnquinteros** [comment]
gracias!
