### ISSUE TITLE
Factory bot no se reconocen en test

### ISSUE THREAD

**Issue by tamaralues** [IIC3745-2020-2/syllabus#60]
Hola, estoy teniendo problemas con Factory Bot. Resulta que intento agregar nuevos factories para completar unos test del controlador, sin embargo, siempre me dice que no está definida. Intenté crearla en un archivo independiente, pero sigue sin funcionar, saben qué puede estar ocurriendo? o a alguien le pasó algo similar?

**Comment by rasaffie** [comment]
Hola,

Me falta detalle para entender qué está pasando. ¿Podrías agregar imágenes con los _logs_ de error, la definición de las _factories_ y los _tests_ en que las usas? También sería útil los links al código en el repositorio de tu grupo.

De todas formas, revisando el código de tu grupo vi que en las _factories_ de `transaction` y `transaction_categories` usas el método `to_create`, que según [la documentación](https://www.rubydoc.info/gems/factory_bot/FactoryBot/Definition#to_create-instance_method) es privado y no se debería usar. Si esas son las _factories_ con las que estás teniendo problemas puede ser por eso.

Saludos,
