### ISSUE TITLE
Duda test de carga

### ISSUE THREAD

**Issue by bimartinez** [IIC3745-2020-2/syllabus#61]
Hola!

Con mi grupo queremos realizar tests de carga sobre nuestras funcionalidades críticas, pero necesitamos autenticar un usuario para esto y no sabemos como hacer para poder incorporar estos datos en loader.io. La idea no es hacer la prueba de carga sobre el _landing_ que es la única vista que tenemos sin permisos.

Muchas gracias!

**Comment by rasaffie** [comment]
Hola,

Con [el plan gratis de Loader](https://loader.io/pricing) puedes hacer que una misma prueba ejecute 2 _requests_. Luego, al [crear un _test_](https://support.loader.io/article/15-creating-a-test) podrás configurar 2 _requests_ en la sección _Client Requests_: una para iniciar sesión y otra para ejecutar la acción. Loader debería [almacenar por defecto las cookies](https://support.loader.io/article/37-do-you-support-cookies), por lo que no necesitarás enviar nada adicional para autenticar la 2º _request_. Sin embargo, es probable que necesites desactivar la validación por [CSRF-Token](https://guides.rubyonrails.org/security.html#csrf-countermeasures) ya que no podrás hacer una _request_ para obtener el _token_ del formulario antes de enviarlo.

También podrías probar con otra herramienta que no tenga estas restricciones, como [Blazemeter](https://www.blazemeter.com/) o [JMeter](https://jmeter.apache.org/).

Cuéntame si alguna alternativa te resulta, saludos.

**Comment by fpattillo** [comment]
Hola!
Pasamos por el mismo problema, y después de deshabilitar la verificación del token, el login devuelve 200 OK, pero después cualquier request adicional que necesite que el usuario esté logueado devuelve un 401 (no autorizado). Saben por qué podría estar pasando esto?
Gracias de antemano!

**Comment by bimartinez** [comment]
Muchas gracias @rasaffie! Efectivamente desactivando la validación por CSRF-Token funcionó realizar el _login_ y luego la _request_. @fpattillo tal vez puede ser problema del _body_ que estás mandando en la _request_ de _login_, nosotros ocupamos este:

```JSON
{
    "user": {
        "email": "el correo",
        "password": "el password"
    }
}
```
