### ISSUE TITLE
Duración video

### ISSUE THREAD

**Issue by vbarreradg** [IIC3745-2020-2/syllabus#62]
Hola! 

Hay posibilidad de alargar el límite de duración del video un poco? Por ejemplo a 15 minutos? Ya que hay muchos detalles que comentar y nos estamos quedando cortos de tiempo.

Muchas gracias!

**Comment by rasaffie** [comment]
Hola,

Lamento no haber respondido ayer: estoy de viaje y recién hoy pude revisar esto. Espero hayan podido adaptar los contenidos del video.

Saludos,
