### ISSUE TITLE
Código Parte A AC01

### ISSUE THREAD

**Issue by fnquinteros** [IIC3745-2020-2/syllabus#7]
Hola!

No entiendo bien el código de la siguiente imágen:

![image](https://user-images.githubusercontent.com/17592014/91916643-a1f4b680-ec8b-11ea-82cb-5a7694eb3b11.png)

La clase `Book` representa a un libro en particular, y `volume` es el número de la saga? por dar un ejemplo, Harry Potter y la cámara secreta se definiría como

`Book.new("Harry Potter", 2, 7)` ??

Si ese es el caso, no entiendo el cálculo de `price_until_complete`. Porqué es relevante el número de la saga? se asume que tengo todos los anteriores?

Por comprar la saga completa se hace un 50% de descuento?

Saludos!
Felipe

**Comment by Hernan4444** [comment]
Hola,

Respondiendo por partes:

> La clase Book representa a un libro en particular, y volume es el número de la saga? 

Si

> Porqué es relevante el número de la saga? se asume que tengo todos los anteriores?

Así es, es solo un cálculo para decir cuánta plata es necesaria desde ese volumen para completar la saga. 

> Por comprar la saga completa se hace un 50% de descuento?

No, simplemente la persona que hace uso de esa función dice que si quiere comprar el volumen 1 y son más de 8 volúmenes en total, dirá que **si compra el volumen 1**  (`true`)  solo si cuenta con la plata para comprar al menos la mitad de la saga. Una interpretación a esto es que no va a empezar a comprar **una saga nueva** si son más de 8 volúmenes y tiene menos plata que la necesaria para adquirir la mitad de saga.

Espero haber resuelto tus dudas
Saludos :v:

**Comment by fnquinteros** [comment]
Buena, gracias
