### ISSUE TITLE
Código parte A actividad

### ISSUE THREAD

**Issue by stmorales** [IIC3745-2020-2/syllabus#8]
Hola!

En el código de la parte A se indica lo siguiente:

![image](https://user-images.githubusercontent.com/42178490/92004335-1bce8380-ed10-11ea-9b46-a9dd48fd2758.png)

Qué tiene que ver el include que nos dicen ahí? Porque por lo que se entiende, en palabras sería: "Si el libro pertenece a las recomendaciones o es el último libro de la saga, se puede comprar". Qué relación tienen ambas afirmaciones?

No entiendo cuál es la lógica de tener recomendaciones?

Ej1: Si un libro es el último de su saga pero es la peor saga de la historia y no me la recomendaron.... me lo puedo comprar igual?

Ej2: SI un libro es el primero de la peor saga de la historia (no recomendado) y NO es el último.... entraría en el "else" y me diría que si puedo comprarlo.

Ese "| |" no debiese ser un "&&"?? O el include no debiese ir en un nivel más arriba?

Muchas gracias! Quedo atento

**Comment by Hernan4444** [comment]
Hola,

En primer lugar indicar que el código no se va a editar, el objetivo de la actividad no es testear si la persona que usa esta función sigue una lógica o no cuando decide comprar un libro, sino que **diseñar casos para verificar que la función haga lo que está programado** y enfrentarlos a casos donde uno ve una función a testear y piensa: "qué rayos es esto". Solo se le dió un contexto para no usar predicados como `lista.include?(A)` 

Ahora, sobre las dudas principales:

> Qué relación tienen ambas afirmaciones?

Para el ayudante que compra libros, si un amigo le recomendó una saga, lo compra sin dudar. Si no se la recomendó, pero por X motivos ya la había empezado y le queda solo 1 volumen para completar la saga, también lo compra porque tiene el toc de no dejar sagas inconclusas cuando solo le falta 1 libro. No se incluyó predicados sobre "tiene el resto de los libros" porque complicaría la actividad con más cosas de forma innecesaria. Puedes ver la afirmación como un `if (A || B) ` y aplicar los conocimiento de testing para ver como asegurar el coverage con ese tipo de branch.

> Ej1: Si un libro es el último de su saga pero es la peor saga de la historia y no me la recomendaron.... me lo puedo comprar igual?

El código dice que si.

> Ej2: SI un libro es el primero de la peor saga de la historia (no recomendado) y NO es el último.... entraría en el "else" y me diría que si puedo comprarlo.

Si tiene más de 7 volúmenes y tiene plata para comprar la mitad de la saga, el código dirá que si. 
Simplemente bajo la lógica del ayudante que decide comprar un libro, le dará una oportunidad a dicho libro porque **no recomendado no implica que sea malo**. Puede que sea nuevo y nadie lo conozca, que efectivamente sea malo para mucha gente pero el ayudante igual quiere darle la oportunidad, que la recomendación venga de una máquina mal entrenada, etc, hay muchas interpretaciones diferentes.

¿Por qué doy énfasis en que hay muchas interpretaciones? para mostrar que es una variable muy subjetiva y que recomiendo fuertemente dejarla de lado para esta actividad, sino generar una lista de sagas, un libro en particular y ver que statement, branch o predicado se cubren y luego como ir cubriendo las demás cosas mediante un libro con otras características.

Saludos :v:

**Comment by stmorales** [comment]
Muchas gracias!! Queda clarísimo!! 

Saludos!
