### ISSUE TITLE
Grafo de control de flujo

### ISSUE THREAD

**Issue by pepina-dev** [IIC3745-2020-2/syllabus#9]
Repito la pregunta que hice hoy en la sesión de consultas:
¿Se puede modelar como un sólo nodo dos líneas que hacen los mismo dentro de un if y elif?
Por ejemplo, si la linea  " mi_variable = True " puede modelarse con  un solo nodo en vez de dos:

if condición
{mi_variable = True }
elif otra_condicion 
{mi_variable = True}

Repuesta (o lo que entendí, corríjanme si estoy mal): No, cada " mi_variable = True "  es un nodo diferente.

**Comment by Hernan4444** [comment]
Hola, validamos la respuesta. Es un No, cada " mi_variable = True " veanlo como un nodo diferente.

Saludos :v:

Edit: el Nn era un "No"

**Comment by pepina-dev** [comment]
Gracias Hernán!
